---
- name: Deploy Grafana monitoring stack to AWS EC2
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: update

    - name: Install required system packages for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      tags: dependencies

    - name: Add Docker’s official GPG key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
      tags: docker

    - name: Set up the Docker repository
      ansible.builtin.shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list
      tags: docker

    - name: Update apt after adding Docker repo
      apt:
        update_cache: yes
      tags: docker

    - name: Install Docker Engine and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      tags: docker

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes
      tags: docker

    - name: Clone your Grafana monitoring repo
      git:
        repo: https://github.com/rideg1337/home-monitoring-stack.git
        dest: /opt/home-monitoring
        version: master
      tags: grafana

    - name: Start Grafana stack with Docker Compose
      shell: docker compose up -d
      args:
        chdir: /opt/home-monitoring
      tags: grafana
